version: '3.10'

services:
  oktta-server:
    depends_on:
      db:
        condition: service_healthy
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${BACKEND_DB_PORT}/${DB_NAME}
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${BACKEND_DB_PORT}:${DB_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data_db.sql:/docker-entrypoint-initdb.d/data_db.sql
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  redis:
    image: redis:alpine
    #    ports:
    #      - "6379:6379"
    networks:
      - mynetwork

volumes:
  pg_data:
    driver: local
  static_volume:
  media_volume:
    driver: local

networks:
  mynetwork:
    external: true